### PR TITLE
New command to reconfigure port speed

### PR DESCRIPTION
**Pull request by gwaibel**
Hi,
I added a new command to set the port speed at runtime if the speed parameter was set to 0 in the static configuration (MAC config table):
sja1105-tool reconfig speed 2 100 => set port2 speed to 100Mb.
I wonder if this is of interest generally...
The command currently only works for the PQRS devices. If desired I could implement it for the ET devices as well, but I have no hardware to test this on.

Regards 
Georg

### CODE REVIEW

**Comment by vladimiroltean** [comment]
Hello,
I like the idea of having this, but I have a few questions/observations:
* How are you integrating this into your setup? When do you know that your PHY link status changed, so as to trigger the MAC reconfiguration?
* In SJA1105 E/T, reading from the MAC reconfiguration table (your `sja1105_mac_config_get`) is not possible. The closest approximation would be to take the MAC entry from the static configuration, but that complicates quickly if we were to expose the possibility to reconfigure multiple MAC properties, not just speed.
* Using your base implementation I got my SJA1105T to reconfigure its MAC link speed (code is valid for SJA1105E as well). Can I add some commits on top of your pull request, for full E/T and P/Q/R/S functionality?

**Comment by gwaibel** [comment]
- Using the sja1105-tool is basically a workaround until we have a proper kernel driver to handle the switch. The idea is to poll the link status of the PHYs by reading its MDIO registers using the phytool or something derived from it and then setting the port speed accordingly. Alternatively, there could be a kernel driver that informs user space about link changes.
- How about storing the MAC reconfig settings temporarily e.g. in the staging area? When uploading a static configuration the reconfig settings can be filled with the values from the static configuration. From then on, the actual settings of the switch are tracked there.
- Of course, feel free to add whatever you want..

**Comment by vladimiroltean** [comment]
> Using the sja1105-tool is basically a workaround until we have a proper kernel driver to handle the switch.

I also privately started to think about how the sja1105-tool could be integrated with a kernel module to implement the missing features. There's a WIP README [here](https://github.com/vladimiroltean/sja1105-tool/tree/master/src/kmod), and my list of thoughts on how the driver would look like can be found [here](https://github.com/vladimiroltean/sja1105-tool/commit/e459320eaaa36976c6bd54d43037b550bc655ffd). Basically extend the sja1105-tool with an out-of-tree kernel module that gets the staging area created by userspace through the request_firmware API, writes it down to the hardware, integrates with the phylib properly and also exposes the 1588 hardware clock nicely.
Currently the module doesn't do much, but the intention is to make the code from libsja1105 be shared with the kmod. This way the staging area can be created, modified etc by one entity, and sanity-checked by the kernel with reasonable code reuse.

> How about storing the MAC reconfig settings temporarily e.g. in the staging area?

You mean rewriting the AUTO speed with the fixed value? But then `sja1105-tool reconfig speed` wouldn't work the second time around, because of the check that the staging area should be in auto mode.

**Comment by vladimiroltean** [comment]
> No, I would not change the static configuration in the sja1105.bin file. Instead I would create a second file, e.g. sja1105_macreconfig.bin, that holds the reconfiguration register values. During the upload of a static configuration, this file is filled with the data from the static configuration. Any reconfig command would modify the file to keep it in sync with the switch.

This is way too complicated for a solution that ends up being incomplete anyway.
* A kernel module can keep the same information in memory.
* Utilities like phytool are also unfit for this purpose, since they work by hijacking the struct phy_device associated with the eth net_device passed as parameter. So basically to perform raw operations on an MDIO bus from userspace, you already need to have a netdevice which has a PHY registered on the MDIO bus that you want to access. Of course, netdevices with fixed link fall short of this criterion. See the [implementation of phy_mii_ioctl](https://github.com/torvalds/linux/blob/master/drivers/net/phy/phy.c#L395-L468).

> Do you know this draft of a kernel module: https://source.codeaurora.org/external/autoivnsw/sja1105x_linux_switchdev?
> It is based on the NXP SJA1105 driver code. I did not really have a look into the code so far. Just found it some days ago.

Yes, however it does not share any code with the sja1105-tool and is of limited usefulness for implementing the missing features in sja1105-tool.

**Comment by gwaibel** [comment]
I know that accessing the PHY registers from user space is quite a dirty hack. A real solution would be a kernel module as you suggested. Will you continue working on the kernel module in the near future?

**Comment by vladimiroltean** [comment]
> Will you continue working on the kernel module in the near future?

I'm only doing that in my spare time since, for better or worse, the current tool we have does the job for our boards. So I can't commit to anything. However, if the kernel-module "sja1105-tool 2.0" ever ends up on feature parity with the userspace-only implementation, I would be glad to merge that back into this repository.

On the other hand, I only see the ability to reconfigure MAC speed as having any usefulness in sja1105-tool in the kmod implementation. So merging this pull request is going to wait at least for a little bit. If you decide to go the route of extending the sja1105-tool in this way, we can continue the discussion [here](https://github.com/vladimiroltean/sja1105-tool).

**Comment by gwaibel** [comment]
This change makes the reconfigure command obsolete: https://github.com/openil/sja1105-tool/pull/35

**Pull request closed without merging**
